services:
  my-node-app:
    build:
      context: .
    image: honganmaki/express:latest
    container_name: my-node-app-container
    ports:
      - "3000:3000"
    labels:
      - "org.label-schema.watchtower.enable=true"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    command:
      - --label-enable
      - --interval
      - "300"
      - --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

