# fly.toml app configuration file generated for exp-blue-bird-9709 on 2025-06-12T22:43:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exp-blue-bird-9709'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
